version: '3.7'

services:
  db: 
    image: postgres:13.3
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bgtadmin
      - POSTGRES_PASSWORD=devadmin
      - POSTGRES_DB=bgt_data
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - . :/usr/src/board-game-tools
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
volumes:
  postgres_data_dev:  
