FROM python:3.8.3
WORKDIR /usr/src/bgt

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt update && apt install -y netcat

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./entrypoint.dev.sh .

COPY . .

ENTRYPOINT ["/usr/src/bgt/entrypoint.dev.sh"]
