# Generated by Django 3.1.7 on 2021-03-21 19:27

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='ToolSession',
            fields=[
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='session_name', unique=True)),
                ('session_name', models.CharField(max_length=50)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bgt_app.userprofile')),
            ],
            options={
                'verbose_name': 'Tool Session',
                'verbose_name_plural': 'Tool Sessions',
            },
        ),
        migrations.CreateModel(
            name='HpTracker',
            fields=[
                ('title', models.CharField(max_length=40)),
                ('hp_value', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=-1000), django.core.validators.MaxValueValidator(limit_value=1000)])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hp_tracker', to='bgt_app.toolsession')),
            ],
            options={
                'verbose_name': 'HP Tracker',
                'verbose_name_plural': 'HP Trackers',
            },
        ),
    ]
