# Generated by Django 3.2.4 on 2021-10-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diestandard',
            options={'verbose_name': 'Standard Die', 'verbose_name_plural': 'Standard Dice'},
        ),
    ]
