# Generated by Django 3.1.7 on 2021-03-23 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hptracker',
            name='hp_value',
            field=models.SmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=-1000), django.core.validators.MaxValueValidator(limit_value=1000)]),
        ),
    ]
