# Generated by Django 3.1.7 on 2021-05-06 17:14

import bgt_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bgt_app", "0002_drawbag_drawbagitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawbagitem",
            name="image",
            field=models.ImageField(upload_to=bgt_app.models.user_directory_path),
        ),
    ]
