# Generated by Django 3.2.4 on 2021-10-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0002_alter_diestandard_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diestandard',
            options={'ordering': ['id'], 'verbose_name': 'Standard Die', 'verbose_name_plural': 'Standard Dice'},
        ),
    ]
