# Generated by Django 3.1.7 on 2021-03-24 04:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0003_auto_20210322_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieGroup',
            fields=[
                ('title', models.CharField(max_length=40)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='die_group', to='bgt_app.toolsession')),
            ],
            options={
                'verbose_name': 'Dice Group',
                'verbose_name_plural': 'Dice Groups',
            },
        ),
        migrations.CreateModel(
            name='DieStandard',
            fields=[
                ('num_sides', models.SmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(limit_value=2), django.core.validators.MaxValueValidator(limit_value=100)])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('die_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='die_standard', to='bgt_app.diegroup')),
            ],
            options={
                'verbose_name': 'Die',
                'verbose_name_plural': 'Dice',
            },
        ),
    ]
