# Generated by Django 3.1.7 on 2021-05-07 17:59

import bgt_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0004_auto_20210506_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawbagitem',
            name='drawn_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='drawbagitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=bgt_app.models.user_directory_path),
        ),
    ]
