# Generated by Django 3.1.7 on 2021-03-24 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0004_diegroup_diestandard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diegroup',
            options={'verbose_name': 'Dice Group', 'verbose_name_plural': 'Die Groups'},
        ),
        migrations.AlterField(
            model_name='diestandard',
            name='die_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bgt_app.diegroup'),
        ),
    ]
