# Generated by Django 3.1.7 on 2021-03-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0005_auto_20210324_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='diestandard',
            name='rolled_value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
