# Generated by Django 3.1.7 on 2021-04-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0008_resource_resourcegroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcegroup',
            options={'verbose_name': 'Resource Group', 'verbose_name_plural': 'Resource Groups'},
        ),
        migrations.AddField(
            model_name='resource',
            name='production_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='tool_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_groups', to='bgt_app.toolsession'),
        ),
    ]
