# Generated by Django 3.1.7 on 2021-04-09 19:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0009_auto_20210402_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('tool_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_groups', to='bgt_app.toolsession')),
            ],
            options={
                'verbose_name': 'Scoring Group',
                'verbose_name_plural': 'Scoring Groups',
            },
        ),
        migrations.CreateModel(
            name='ScoringCategorySimple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('points', models.SmallIntegerField(default=0)),
                ('scoring_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_categories_simple', to='bgt_app.scoringgroup')),
            ],
            options={
                'verbose_name': 'Simple Scoring Category',
                'verbose_name_plural': 'Simple Scoring Categories',
            },
        ),
        migrations.CreateModel(
            name='ScoringCategoryPointsPerItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('points', models.SmallIntegerField(default=0)),
                ('scoring_items_qty', models.SmallIntegerField(default=0)),
                ('points_per_item', models.SmallIntegerField(default=0)),
                ('scoring_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_categories_points_per_item', to='bgt_app.scoringgroup')),
            ],
            options={
                'verbose_name': 'Points Per Item Scoring Category',
                'verbose_name_plural': 'Points Per Item Scoring Categories',
            },
        ),
        migrations.CreateModel(
            name='ScoringCategoryItemsPerPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('points', models.SmallIntegerField(default=0)),
                ('scoring_items_qty', models.SmallIntegerField(default=0)),
                ('items_per_point_trigger', models.SmallIntegerField(default=0)),
                ('points_per_point_trigger', models.SmallIntegerField(default=0)),
                ('round_up_down', models.CharField(choices=[('up', 'up'), ('down', 'down')], max_length=5)),
                ('scoring_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_categories_items_per_point', to='bgt_app.scoringgroup')),
            ],
            options={
                'verbose_name': 'Items Per Point Scoring Category',
                'verbose_name_plural': 'Items Per Point Scoring Categories',
            },
        ),
    ]
