# Generated by Django 3.1.7 on 2021-04-20 00:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0011_auto_20210415_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('rounding', models.CharField(choices=[('up', 'round up'), ('down', 'round down'), ('none', 'no rounding')], max_length=5)),
                ('points', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=-1000), django.core.validators.MaxValueValidator(limit_value=1000)])),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_categories_simple', to='bgt_app.scoringgroup')),
            ],
            options={
                'verbose_name': 'Scoring Category',
                'verbose_name_plural': 'Scoring Categories',
            },
        ),
        migrations.RemoveField(
            model_name='scoringcategorypointsperitem',
            name='group',
        ),
        migrations.RemoveField(
            model_name='scoringcategorysimple',
            name='group',
        ),
        migrations.DeleteModel(
            name='ScoringCategoryItemsPerPoint',
        ),
        migrations.DeleteModel(
            name='ScoringCategoryPointsPerItem',
        ),
        migrations.DeleteModel(
            name='ScoringCategorySimple',
        ),
    ]
