# Generated by Django 3.1.7 on 2021-04-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0012_auto_20210419_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringcategory',
            name='type',
            field=models.CharField(choices=[('simple', 'simple'), ('items_per_point', 'items per point'), ('points_per_item', 'points_per_item')], default='simple', max_length=15),
        ),
        migrations.AlterField(
            model_name='scoringcategory',
            name='rounding',
            field=models.CharField(choices=[('up', 'round up'), ('down', 'round down'), ('none', 'no rounding')], default='none', max_length=5),
        ),
    ]
