# Generated by Django 3.1.7 on 2021-04-21 04:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0013_auto_20210419_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringcategory',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_categories', to='bgt_app.scoringgroup'),
        ),
        migrations.AlterField(
            model_name='scoringcategory',
            name='type',
            field=models.CharField(choices=[('simple', 'simple'), ('items_per_point', 'items per point'), ('points_per_item', 'points per item')], default='simple', max_length=15),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(choices=[('black', 'black'), ('white', 'white'), ('green', 'green'), ('blue', 'blue'), ('yellow', 'yellow'), ('purple', 'purple'), ('orange', 'orange'), ('red', 'red'), ('brown', 'brown')], max_length=10)),
                ('score', models.IntegerField(max_length=6)),
                ('scoring_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='bgt_app.scoringgroup')),
                ('tool_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='bgt_app.toolsession')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
    ]
