# Generated by Django 3.1.7 on 2021-04-21 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0014_auto_20210420_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoringcategory',
            old_name='points',
            new_name='items_per_group',
        ),
        migrations.RemoveField(
            model_name='scoringcategory',
            name='type',
        ),
        migrations.AddField(
            model_name='scoringcategory',
            name='points_gained_or_lost',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=-1000), django.core.validators.MaxValueValidator(limit_value=1000)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.SmallIntegerField(max_length=6),
        ),
    ]
