# Generated by Django 3.1.7 on 2021-04-21 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0016_auto_20210420_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=-1000), django.core.validators.MaxValueValidator(limit_value=1000)]),
        ),
    ]
