# Generated by Django 3.1.7 on 2021-04-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0017_auto_20210420_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='scoring_group',
        ),
        migrations.AddField(
            model_name='player',
            name='scoring_groups',
            field=models.ManyToManyField(null=True, related_name='players', to='bgt_app.ScoringGroup'),
        ),
    ]
