# Generated by Django 3.1.7 on 2021-04-30 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgt_app', '0022_gametimer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gametimer',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='gametimer',
            name='saved_duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
